name: PR Preview
on: pull_request

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: technote-space/get-diff-action@v6
        id: get-diff
        with:
          PATTERNS: |
            **/*.ts
      - name: HTML Preview
        id: html_preview
        if: env.GIT_DIFF
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: "./web/src/index.html"
      - name: Create commit comment
        if: env.GIT_DIFF
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            - Preview API Documentation: [index.html][1]

            [1]: ${{ steps.html_preview.outputs.url }}
